### ISSUE TITLE
annotation not available in Python 3.6.8

### ISSUE THREAD

**Issue by Kavan72** [altdesktop/python-dbus-next#10]
```py
Traceback (most recent call last):
  File "/media/kavan/DATA/**/**/main.py", line 4, in <module>
    from dbus_next.aio import MessageBus
  File "/media/kavan/DATA/**/**/venv_3_6/lib/python3.6/site-packages/dbus_next/__init__.py", line 1, in <module>
    from . import aio
  File "/media/kavan/DATA/**/**/venv_3_6/lib/python3.6/site-packages/dbus_next/aio/__init__.py", line 1, in <module>
    from .message_bus import MessageBus
  File "/media/kavan/DATA/**/**/venv_3_6/lib/python3.6/site-packages/dbus_next/aio/message_bus.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```
ik this is easy. i will fix this and open new PR when i have time

**Comment by acrisci** [comment]
I think the right way to do it is to remove the `__future__` import and use a string for any annotation that refers to the self class.

**Comment by Kavan72** [comment]
yep this is good way

**Comment by Gunni** [comment]
This leaves this library broken on CentOS 7.

**Comment by acrisci** [comment]
4bcf72a

**Comment by ryao-mdanderson** [comment]
I hit this problem today 2021.12.29, May anyone tell me the exact fix? How should I do?

Thanks!!!

**Comment by acrisci** [comment]
This issue has been fixed. Make sure you are on the latest code then open a new issue.

**Comment by ryao-mdanderson** [comment]
@acrisci Sorry I was working on application galaxy and hit this similar issue. Thanks for correcting me.
