### ISSUE TITLE
Calling a method without Arguments?

### ISSUE THREAD

**Issue by akloster** [altdesktop/python-dbus-next#29]
I am trying to call the "StartNotify" method on the "bluez.org.GattCharacteristic1" interface of a Service. According to the introspection the method doesn't have arguments.

Now I get this:

```
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    loop.run_until_complete(main())
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "test.py", line 103, in main
    await mm.run()
  File "test.py", line 91, in run
    x = (await char.call_start_notify([])).value
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/site-packages/dbus_next/aio/proxy_object.py", line 77, in method_fn
    body=list(args)))
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/site-packages/dbus_next/aio/message_bus.py", line 240, in call
    self._call(msg, reply_handler)
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/site-packages/dbus_next/message_bus.py", line 462, in _call
    self.send(msg)
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/site-packages/dbus_next/aio/message_bus.py", line 255, in send
    asyncio.ensure_future(self._loop.sock_sendall(self._sock, msg._marshall()))
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/site-packages/dbus_next/message.py", line 206, in _marshall
    body_block = Marshaller(self.signature, self.body)
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/site-packages/dbus_next/_private/marshaller.py", line 8, in __init__
    self.signature_tree.verify(body)
  File "/home/andi/anaconda3/envs/py37/lib/python3.7/site-packages/dbus_next/signature.py", line 328, in verify
    f'The body has the wrong number of types (got {len(body)}, expected {len(self.types)})'
dbus_next`

Any idea what this could mean?

**Comment by acrisci** [comment]
It looks like you are calling the method with an argument.

```
x = (await char.call_start_notify([])).value
```

Should be:

```
x = (await char.call_start_notify()).value
```

**Comment by akloster** [comment]
Oh I'm sorry. It works now. I thought I had tried it without any arguments. Anyway, the .value is also wrong, because the coroutine returns None.

**Comment by michallowasrzechonek-silvair** [comment]
@acrisci a related question: does dbus-next support passing file descriptors?

GATT has a nicer API called `AcquireNotify`, returning an open file you can (asynchronously) read from to receive data transferred over the BLE characteristic.

**Comment by michallowasrzechonek-silvair** [comment]
By looking at the code I don't think it actually works...

As far as I understand, it's not enough to just marshall the descriptor value - one should use `sendmsg` and `recvmsg` on the socket in order to receive ancillary `SOL_SOCKET` data.

**Comment by akloster** [comment]
Yes, my issue is resolved.

I am trying to figure out how to get notified by a GATT device, so I'm interested in the descriptor thing. Unfortunately, I can't find a lot on how this is supposed to work.

**Comment by akloster** [comment]
I think notification is supposed to work by calling "startNotify" on the Characteristic1 Interface and then subscribing to the propertyChanged signal of the Properties Interface...

**Comment by michallowasrzechonek-silvair** [comment]
Yes. Just make sure to subscribe to `PropertiesChanged` *first*, then call `StartNotify`. You will get notifications about changed `Value` property of the characteristic. Something like this:

```python
def on_properties_changed(iface, changed, invalidated):
    if iface != "bluez.org.GattCharacteristic1":
        return

    for name, variant in changed.items():
        if name == "Value":
            print("Received", variant.value.hex())

introspection = await self.bus.introspect("org.bluez", char_path)
char_proxy = self.bus.get_proxy_object("org.bluez", char_path, introspection)

props_iface = char_proxy.get_interface("org.freedesktop.DBus.Properties")
props_iface.on_properties_changed(on_properties_changed)        
```
