### ISSUE TITLE
Python 4.0 annotation compatibility for high level service

### ISSUE THREAD

**Issue by acrisci** [altdesktop/python-dbus-next#3]
Using the `__future__` annotations (default for python 3.8 to 4.0) will break the current way I get annotations from functions in the high level service.

**Comment by Kavan72** [comment]
that's why not working on 3.6.8 this is so annoying

**Comment by acrisci** [comment]
It should work fine on 3.6.8 without the `__future__` annotations. What is the problem?

**Comment by Kavan72** [comment]
```py
Traceback (most recent call last):
  File "/media/kavan/DATA/**/**/main.py", line 4, in <module>
    from dbus_next.aio import MessageBus
  File "/media/kavan/DATA/**/**/venv_3_6/lib/python3.6/site-packages/dbus_next/__init__.py", line 1, in <module>
    from . import aio
  File "/media/kavan/DATA/**/**/venv_3_6/lib/python3.6/site-packages/dbus_next/aio/__init__.py", line 1, in <module>
    from .message_bus import MessageBus
  File "/media/kavan/DATA/**/**/venv_3_6/lib/python3.6/site-packages/dbus_next/aio/message_bus.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by acrisci** [comment]
I should be able to fix this because I only use that for type hints.

**Comment by Kavan72** [comment]
that nice cuz right now its only support on 3.7+

**Comment by acrisci** [comment]
Make a new issue to discuss it because this is a separate issue. You are free to work on it if you want. I won't get around to this until I do some other stuff.

**Comment by acrisci** [comment]
It seems like the breaking change didn't make it into python 3.8 so we can put this off. The test suite works fine. Remember to test this again with the next release.

**Comment by alebastr** [comment]
We started testing python packages in Fedora with python 3.10.0 pre-releases and found that several tests in `dbus_next` are failing:
```
ERROR test/test_big_message.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/test_fd_passing.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/client/test_methods.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/client/test_properties.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/client/test_signals.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/service/test_decorators.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/service/test_methods.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/service/test_properties.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/service/test_signals.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
ERROR test/service/test_standard_interfaces.py - dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
```

<details>
<summary>full test log</summary>

```
+ /usr/bin/dbus-run-session -- /usr/bin/pytest
============================= test session starts ==============================
platform linux -- Python 3.10.0a6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /builddir/build/BUILD/python-dbus-next-0.2.2, configfile: pytest.ini
plugins: timeout-1.4.2, asyncio-0.14.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 38 items / 10 errors / 28 selected

==================================== ERRORS ====================================
__________________ ERROR collecting test/test_big_message.py ___________________
test/test_big_message.py:10: in <module>
    class ExampleInterface(ServiceInterface):
test/test_big_message.py:15: in ExampleInterface
    def echo_bytes(self, what: 'ay') -> 'ay':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:102: in decorator
    wrapped.__dict__['__DBUS_METHOD'] = _Method(fn, fn_name, disabled=disabled)
dbus_next/service.py:38: in __init__
    in_args.append(intr.Arg(param.annotation, intr.ArgDirection.IN, param.name))
dbus_next/introspection.py:43: in __init__
    tree = SignatureTree._get(signature)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
___________________ ERROR collecting test/test_fd_passing.py ___________________
test/test_fd_passing.py:15: in <module>
    class ExampleInterface(ServiceInterface):
test/test_fd_passing.py:21: in ExampleInterface
    def ReturnsFd(self) -> 'h':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:102: in decorator
    wrapped.__dict__['__DBUS_METHOD'] = _Method(fn, fn_name, disabled=disabled)
dbus_next/service.py:44: in __init__
    for type_ in SignatureTree._get(inspection.return_annotation).types:
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
_________________ ERROR collecting test/client/test_methods.py _________________
test/client/test_methods.py:12: in <module>
    class ExampleInterface(ServiceInterface):
test/client/test_methods.py:21: in ExampleInterface
    def EchoInt64(self, what: 'x') -> 'x':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:102: in decorator
    wrapped.__dict__['__DBUS_METHOD'] = _Method(fn, fn_name, disabled=disabled)
dbus_next/service.py:38: in __init__
    in_args.append(intr.Arg(param.annotation, intr.ArgDirection.IN, param.name))
dbus_next/introspection.py:43: in __init__
    tree = SignatureTree._get(signature)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
_______________ ERROR collecting test/client/test_properties.py ________________
test/client/test_properties.py:10: in <module>
    class ExampleInterface(ServiceInterface):
test/client/test_properties.py:19: in ExampleInterface
    def SomeProperty(self) -> 's':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:300: in decorator
    return _Property(fn, options=options)
dbus_next/service.py:226: in __init__
    tree = SignatureTree._get(sig.return_annotation)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
_________________ ERROR collecting test/client/test_signals.py _________________
test/client/test_signals.py:10: in <module>
    class ExampleInterface(ServiceInterface):
test/client/test_signals.py:15: in ExampleInterface
    def SomeSignal(self) -> 's':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:171: in decorator
    signal = _Signal(fn, fn_name, disabled)
dbus_next/service.py:119: in __init__
    signature_tree = SignatureTree._get(signature)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
_______________ ERROR collecting test/service/test_decorators.py _______________
test/service/test_decorators.py:5: in <module>
    class ExampleInterface(ServiceInterface):
test/service/test_decorators.py:13: in ExampleInterface
    def some_method(self, one: 's', two: 's') -> 's':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:102: in decorator
    wrapped.__dict__['__DBUS_METHOD'] = _Method(fn, fn_name, disabled=disabled)
dbus_next/service.py:38: in __init__
    in_args.append(intr.Arg(param.annotation, intr.ArgDirection.IN, param.name))
dbus_next/introspection.py:43: in __init__
    tree = SignatureTree._get(signature)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
________________ ERROR collecting test/service/test_methods.py _________________
test/service/test_methods.py:8: in <module>
    class ExampleInterface(ServiceInterface):
test/service/test_methods.py:13: in ExampleInterface
    def echo(self, what: 's') -> 's':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:102: in decorator
    wrapped.__dict__['__DBUS_METHOD'] = _Method(fn, fn_name, disabled=disabled)
dbus_next/service.py:38: in __init__
    in_args.append(intr.Arg(param.annotation, intr.ArgDirection.IN, param.name))
dbus_next/introspection.py:43: in __init__
    tree = SignatureTree._get(signature)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
_______________ ERROR collecting test/service/test_properties.py _______________
test/service/test_properties.py:9: in <module>
    class ExampleInterface(ServiceInterface):
test/service/test_properties.py:19: in ExampleInterface
    def string_prop(self) -> 's':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:300: in decorator
    return _Property(fn, options=options)
dbus_next/service.py:226: in __init__
    tree = SignatureTree._get(sig.return_annotation)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
________________ ERROR collecting test/service/test_signals.py _________________
test/service/test_signals.py:11: in <module>
    class ExampleInterface(ServiceInterface):
test/service/test_signals.py:20: in ExampleInterface
    def signal_simple(self) -> 's':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:171: in decorator
    signal = _Signal(fn, fn_name, disabled)
dbus_next/service.py:119: in __init__
    signature_tree = SignatureTree._get(signature)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
__________ ERROR collecting test/service/test_standard_interfaces.py ___________
test/service/test_standard_interfaces.py:17: in <module>
    class ExampleComplexInterface(ServiceInterface):
test/service/test_standard_interfaces.py:24: in ExampleComplexInterface
    def Foo(self) -> 'y':
/usr/lib64/python3.10/typing.py:1751: in wrapped_decorator
    func = decorator(*args, **kwds)
dbus_next/service.py:300: in decorator
    return _Property(fn, options=options)
dbus_next/service.py:226: in __init__
    tree = SignatureTree._get(sig.return_annotation)
dbus_next/signature.py:320: in _get
    SignatureTree._cache[signature] = SignatureTree(signature)
dbus_next/signature.py:332: in __init__
    (type_, signature) = SignatureType._parse_next(signature)
dbus_next/signature.py:65: in _parse_next
    raise InvalidSignatureError(f'got unexpected token: "{token}"')
E   dbus_next.errors.InvalidSignatureError: got unexpected token: "'"
=========================== short test summary info ============================
ERROR test/test_big_message.py - dbus_next.errors.InvalidSignatureError: got ...
ERROR test/test_fd_passing.py - dbus_next.errors.InvalidSignatureError: got u...
ERROR test/client/test_methods.py - dbus_next.errors.InvalidSignatureError: g...
ERROR test/client/test_properties.py - dbus_next.errors.InvalidSignatureError...
ERROR test/client/test_signals.py - dbus_next.errors.InvalidSignatureError: g...
ERROR test/service/test_decorators.py - dbus_next.errors.InvalidSignatureErro...
ERROR test/service/test_methods.py - dbus_next.errors.InvalidSignatureError: ...
ERROR test/service/test_properties.py - dbus_next.errors.InvalidSignatureErro...
ERROR test/service/test_signals.py - dbus_next.errors.InvalidSignatureError: ...
ERROR test/service/test_standard_interfaces.py - dbus_next.errors.InvalidSign...
!!!!!!!!!!!!!!!!!!! Interrupted: 10 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 10 errors in 1.09s ==============================
```
</details>

Fedora bug: <https://bugzilla.redhat.com/show_bug.cgi?id=1936945>

I traced the failure to the changed behavior of `inspect.Signature.return_annotation`:
```
<mock-chroot> sh-5.1# python3
Python 3.10.0a6 (default, Mar  2 2021, 00:00:00) [GCC 11.0.0 20210210 (Red Hat 11.0.0-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def test() -> 'ay':
...     pass
...
>>> import inspect
>>> inspect.signature(test).return_annotation
"'ay'"
```
caused by [`[typing] PEP 563: Postponed evaluation of annotations: enable it by default in Python 3.10`](https://bugs.python.org/issue38605)

This seems to be matching the issue described here.

**Comment by acrisci** [comment]
Ok at least it's good to see how this breaking change played out. It shouldn't be too hard to fix.
